version: "3.9"

services:
  nginx:
    image: nginx:1.27-alpine
    ports:
      - "8081:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    build: .
    container_name: lab6_php
    volumes:
      - ./www:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - redis
      - clickhouse

  redis:
    image: redis:7
    container_name: lab6_redis
    ports:
      - "6379:6379"

  clickhouse:
    image: clickhouse/clickhouse-server:24
    container_name: lab6_clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"

volumes:
  redis_data:
  ch_data:

