version: '3.8'
services:
  nginx:
    image: nginx:alpine
    container_name: lab6_nginx
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - redis

  php:
    build: .
    container_name: lab6_php
    volumes:
      - ./www:/var/www/html
    expose:
      - "9000"
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: lab6_redis
    ports:
      - "6379:6379"

volumes:
  redis_data: