version: '3.8'
services:
  php:
    build: .
    container_name: lab7_php
    volumes:
      - ./www:/var/www/html
    expose:
      - "9000"
    depends_on:
      - kafka

  zookeeper:
    image: zookeeper:3.8
    container_name: lab7_zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1

  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    container_name: lab7_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper

  nginx:
    image: nginx:alpine
    container_name: lab7_nginx
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      
  worker:
    build: .
    container_name: lab7_worker
    command: php worker.php
    volumes:
      - ./www:/var/www/html
    depends_on:
      - kafka
    restart: unless-stopped